services:
  facility-db:
    image: "postgres:16.4-alpine"
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - facility_db:/var/lib/postgresql/data

  facility-api:
    build:
      dockerfile: api.Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - facility-db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://facility-db:5432/facility
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - APPLICATION_SECURITY_JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./public:/public

  facility-ui:
    build:
      dockerfile: app.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./public/images/upload:/srv/images/upload
      - ./prod.Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  facility_db:
