services:
  db:
    image: "postgres:17.2-alpine"
    env_file: .env
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - facility_db:/var/lib/postgresql/data

  app:
    ports:
      - "80:3000"
    build: .
    env_file: .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${PGUSER}:${PGPASSWORD}@db:5432/${PGDATABASE}
      - NODE_ENV=production
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - ./public/images/upload:/srv/public/images/upload

volumes:
  facility_db:
