name: build

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: facility
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: install
        run: bun install --frozen-lockfile
      - name: build
        run: bun run build
      - name: start
        env:
          NODE_ENV: production
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/facility
          EMAIL_USER: "${{ secrets.EMAIL_USER }}"
          EMAIL_PASS: "${{ secrets.EMAIL_PASS }}"
        run: |
          bun run start &
          bunx wait-on http://localhost:3000 -t 5s && echo ok

