name: build

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:

jobs:
  build-java-prod:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: maven
        run: ./mvnw clean package
        working-directory: ./api
        env:
          SPRING_PROFILES_ACTIVE: prod
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
          JWT_SECRET_KEY: 8RSmvTdZ90BVGF94aq/2+Wx+M1zW3UOYdN6yex20008PpD2jRJqgzln/d9QVRknzPEfx/xwHevC61dRyqXn8nWgHv+AJ/toTltRV6dV5d6HoTb8eHEjHG0G4ic5SoIKgjAf8dFIZq3RrhwnVNecXJ+Dw/HxNGTF1R5HWn7qJ0oLTCzmjZ4daIJiB/WkYWSUSpxEq0QuRPaDkLWfqJabBVHnEh/ZRM1520Wr5pIChaJPBCbvRPEqdkG+3M+XPLJSWddTPcw/WBZIbUOh1n4fYuOMa4kjbksPrabASnzsYjrs2gWXZWARp4l7oPKMzrX+oPpU1XTsmgs9vs06kN8UoBQ==

  build-java-dev:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: maven
        run: ./mvnw clean package
        working-directory: ./api

  build-npm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: run prettier
        run: |
          npm ci
          npm run build
