name: build

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - name: run prettier
        run: |
          npm ci
          npm run build
        env:
          NODE_ENV: production
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgres
          JWT_SECRET_KEY: 3PuqrpPQjSyGVOgRgqbwc4uAkgYpxSjpTnvzByA7yAoVxvBSLd3UiBGD2E7c1TejB54/gK59rBONutoMqbiZfDK5uCtWT3XJT4xxQW2sWs8vv7q4IBXxeS0C5wWZ+yngyjavrZhkO/B33HZyCLx/hJf8WAFBO2Aow88kFjmwZoPOrcucbDUPAdqsuv05OKW4AgZU9XFdPuZvIS7dFw3+lvcI79wL6QQE8W2bNPDf9at+oXrVi8PA39aIB2nNAMsZUT+CqSADikNBjuxfY3BOLALjxB9If9RDLuip57znekUAnLzVo8P8opZqbsIdHT/vvwO+qocVC2G91Dtg5Zh6heKRyG2KLRWmtjRrOVOLYI5YrDFip3z0wXwVRbqIcrOiV7T3d/oFQwY5areUzSspsWEixoQttejrWz1r0ROOLyE76bZl+25aIm2GPgqq7ZZ18Wu7aZf82F4Z7o52hnVF8RyxUgsnNeExeDl+0EZQYVNlJBIt/np52p6FEuHlGEUACg/sHig7yAwYlYQU1VBmg/LLU0R75mLKSwhtqJID2sed2FS+Lg86jf4PX/ATOmLyCuZ9yBdt/PPriYOJJYU4AIOBINbWaQD1rgrD5IcZmwesfGzFHkqsFa2Y/QJZy1PJWJA8jCkPGYu1EbmV8HzPSG6L+w0A8Xgr2mdL32OsoUw=
