name: lint

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: run prettier
        working-directory: ./www
        run: |
          npm ci
          npx prettier -w .. --ignore-path .gitignore --ignore-path ../.gitignore --ignore-path ../api/.gitignore
      - name: diff
        id: diff
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: commit
        if: steps.diff.outputs.modified == 'true'
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -am "chore: format with prettier"
          git push
      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: maven
        run: ./mvnw clean
        working-directory: ./api
      - name: diff
        id: diff_java
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: commit
        if: steps.diff_java.outputs.modified == 'true'
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -am "chore: format java files"
          git push
