name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: install dependencies
        run: bun install --frozen-lockfile
      - name: run biome
        run: bunx biome check --write --unsafe .
      - name: run prettier
        run: bunx prettier -w .
      - name: diff
        id: diff
        run: |
          git add .
          git diff --staged --quiet || echo "modified=true" >> $GITHUB_OUTPUT
      - uses: planetscale/ghcommit-action@v0.2.5
        name: commit
        if: steps.diff.outputs.modified == 'true'
        with:
          commit_message: "chore: fix linting errors and format"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
